### ISSUE TITLE
Instalation script problem

### ISSUE THREAD

**Issue by cshenry** [ModelSEED/Model-SEED-core#2] opened 2011-09-12 16:36 UTC
After setting the the parameters in the setting under config.

After running the script I get:

```
raphyz@laptopraphyz ~/phd/ModelSEED/bin $ ./configureModelSEED.sh 
mkdir /config: Permission denied at ../lib/ModelSEED/ModelSEEDScripts/configureModelSEED.pl line 71
```

I have also tried it when pointing to the config file (I saw in the perl that you expect parameters although in the install you did not mention them.

Remember that I am not running as a root user and as such I do not have permissions to create folders under /.
Submitted by Raphy Zareki

**Comment by devoid** [comment] 2011-09-12 22:28
This should be fixed now. I've updated the code to be more `cwd` agnostic.

**Comment by raphyz** [comment] 2011-09-13 05:09
It still does not work, after taking the new version from now with the same problem
raphyz@laptopraphyz ~/phd/ModelSEED/bin $ ./configureModelSEED.sh 
mkdir /config: Permission denied at /home/raphyz/phd/ModelSEED/bin/../lib/ModelSEED/ModelSEEDScripts/configureModelSEED.pl line 70

**Comment by devoid** [comment] 2011-09-13 05:28
Have you set the installation path? It should be:

```
Installation Path:~/phd/ModelSEED
```

If it's empty it will try to put it in root. It should really error out though. I'll fix that.

**Comment by raphyz** [comment] 2011-09-13 05:40
Hi Scott

Here is my Settings.txt

located in the config directory.

How does the script know where this file is located?

Raphy

**Closed as completed** 2011-09-13 20:03 UTC

**Comment by devoid** [comment] 2011-09-13 21:35
Ok so this issue was caused by poor parsing of the configuration file, resulting in the `Installation Path` switching to `/` when if ran into trouble. I've rewritten the configuration system, now at `bin/ms-config`. 

Usage is:
`$ ms-config load filename` loads a configuration file (default is `config/Settings.conf`)
`$ ms-config unload` removes all changes made by load
`$ ms-config reload filename` performs unload then load.

Let me know if this works better.
