### ISSUE TITLE
testing the installation

### ISSUE THREAD

**Issue by raphyz** [ModelSEED/Model-SEED-core#15] opened 2011-09-14 05:19 UTC
In the installation instructions there is an entry regarding how to test the environment after installation.

.8) Test environment by running Model Driver with no arguments:
    a.) Run this script: Model-SEED-core/bin/ModelDriver.(sh/cmd)

When doing so I get:
./ModelDriver.sh 
Function name must be specified as input arguments!

I can not learn from this if al is OK or not.
Either say that this is the expected behavior or change the script report

**Comment by devoid** [comment] 2011-09-14 05:44
As far as I know that's the expected behavior (i.e. that's what it did for me). But you are right, it's not clear from the instructions. I think we'll change those to a short demo and/or successful return from the test suite.

**Comment by cshenry** [comment] 2011-09-15 21:05
Excellent point Raphy. I will adjust the behavior of this script, or provide an alternative script to test the environment. Really, ideally we want to run some sort of "prove" to test each significant functionality.

**Comment by devoid** [comment] 2011-09-15 21:52
This will require an update to the current test scripts. In truth this is
actually pretty good because we can create a `Debug.conf` file that contains
configuration to use clean datasets that won't mess with the core-data or an
existing users data. This is on my list of things to do, but it will take a
bit of time.

~ Scott

**Comment by cshenry** [comment] 2011-09-29 21:00
I did change the default behavior of ModelDriver.pl to provide a more intuitive response. However, I will not close this issue at this time. I believe this issue cannot be closed until we have a script in the bin directory that allows the user to run a "prove" on their model SEED installation, demonstrating that all tests pass successfully.

**Comment by devoid** [comment] 2011-10-10 18:14
The testing scripts are now working properly. There are 2 errors (see #44) but overall the test routines are running properly. See http://bionet.mcs.anl.gov/index.php/Using_the_Model_SEED#Testing_Model_SEED for how to run the `prove` scripts.

**Closed as completed by devoid** 2011-10-10 18:14 UTC
